@startuml
'https://plantuml.com/class-diagram

class Solution42{
    main()
     ' fileReader read = new fileReader
     ' read.
}

class fileReader{
    - parseData() - returns Arraylist<String>
     ' take in the data from the file
     ' store them into an array list and return the data
}

fileReader-->Solution42

@enduml